job('First_Maven_Project_Via_DSL') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on my github")
    scm {
	git ("https://github.com/hbessala/jenkins-training.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
